### ISSUE TITLE
JavaScriptでURLのパラメータやアンカーを判断して処理を変更する方法

### ISSUE THREAD

**Issue by dennougorilla** [skymth/wano_intern2018#25]
https://www.tam-tam.co.jp/tipsnote/javascript/post9911.html

**Comment by soeyusuke** [comment]
@dennougorilla 

```
http://localhost:9090/book/api/get/${this.$route.params.title}
```
こんな感じで値をとってこれるはず

- [https://github.com/soeyusuke/library-app/blob/master/src/components/getinfo.vue#L100](https://github.com/soeyusuke/library-app/blob/master/src/components/getinfo.vue#L100)
